version: '3.8'

services:
  db:
    image: postgres:13
    container_name: lesson_api_db
    environment:
      POSTGRES_DB: ${DB_NAME}     
      POSTGRES_USER: ${DB_USER}    
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/test.sql:/docker-entrypoint-initdb.d/test.sql
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge